services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:ollama
    restart: always
    ports:
      - 11434:11434
      - 3000:8080
    volumes:
      - ollama:/root/.ollama
      - open-webui:/app/backend/data
